# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 242ae9323426848d42cb7e5e94a32930e83fe96194432a2e36204118b833a44e416555e3535208067c3b13eb2467a37306e143a41259ada2d6a57188c7cbbcb7

test:
  secret_key_base: 0007dda30ff0b05759e9b99db77bd0c5c3e22607ec66209c8cf55f8cc0bd4e945b036fcdd0a69c8930fd2dee80831044f51f2f2f3d2c18d50275629ba61a0649

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
