# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31ba409d0ae8dbe8cc1c4196e9b42316e4ba9743fe44ec453ab16a99a4394afa31ba5a7142a19a180d73aca317647e351de4cd30bf62cca38107ad524b4d7c4c

test:
  secret_key_base: 4c031d79c0aa2a0749bd732cdff0e8dcedd2b0d6cabebc1db935bd15d1b4f2350c77360ad952b3a37c5d09b151ee25e9a7398432d7aee06a1bf71ecd82298ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
